name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-east4-docker.pkg.dev
        docker build -t us-east4-docker.pkg.dev/nodal-unity-424508-u9/the-book-store/nginx:latest
        docker push us-east4-docker.pkg.dev/nodal-unity-424508-u9/the-book-store/nginx:latest
